"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
compile command:
python -m grpc_tools.protoc -I=p2pfl/proto --python_out=p2pfl/proto --grpc_python_out=p2pfl/proto p2pfl/proto/node.proto --mypy_out=p2pfl/proto
"""

import abc
import collections.abc
import google.protobuf.empty_pb2
import grpc
import grpc.aio # type: ignore
from p2pfl.communication.protocols.protobuff.proto import node_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_NodeServiceshandshakeType = typing_extensions.TypeVar(
    '_NodeServiceshandshakeType',
    grpc.UnaryUnaryMultiCallable[
        node_pb2.HandShakeRequest,
        node_pb2.ResponseMessage,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        node_pb2.HandShakeRequest,
        node_pb2.ResponseMessage,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        node_pb2.HandShakeRequest,
        node_pb2.ResponseMessage,
    ],
)

_NodeServicesdisconnectType = typing_extensions.TypeVar(
    '_NodeServicesdisconnectType',
    grpc.UnaryUnaryMultiCallable[
        node_pb2.HandShakeRequest,
        google.protobuf.empty_pb2.Empty,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        node_pb2.HandShakeRequest,
        google.protobuf.empty_pb2.Empty,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        node_pb2.HandShakeRequest,
        google.protobuf.empty_pb2.Empty,
    ],
)

_NodeServicessendType = typing_extensions.TypeVar(
    '_NodeServicessendType',
    grpc.UnaryUnaryMultiCallable[
        node_pb2.RootMessage,
        node_pb2.ResponseMessage,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        node_pb2.RootMessage,
        node_pb2.ResponseMessage,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        node_pb2.RootMessage,
        node_pb2.ResponseMessage,
    ],
)

class NodeServicesStub(typing.Generic[_NodeServiceshandshakeType, _NodeServicesdisconnectType, _NodeServicessendType]):
    @typing.overload
    def __init__(self: NodeServicesStub[
        grpc.UnaryUnaryMultiCallable[
            node_pb2.HandShakeRequest,
            node_pb2.ResponseMessage,
        ],
        grpc.UnaryUnaryMultiCallable[
            node_pb2.HandShakeRequest,
            google.protobuf.empty_pb2.Empty,
        ],
        grpc.UnaryUnaryMultiCallable[
            node_pb2.RootMessage,
            node_pb2.ResponseMessage,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: NodeServicesStub[
        grpc.aio.UnaryUnaryMultiCallable[
            node_pb2.HandShakeRequest,
            node_pb2.ResponseMessage,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            node_pb2.HandShakeRequest,
            google.protobuf.empty_pb2.Empty,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            node_pb2.RootMessage,
            node_pb2.ResponseMessage,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    handshake: _NodeServiceshandshakeType

    disconnect: _NodeServicesdisconnectType

    send: _NodeServicessendType

NodeServicesAsyncStub: typing_extensions.TypeAlias = NodeServicesStub[
    grpc.aio.UnaryUnaryMultiCallable[
        node_pb2.HandShakeRequest,
        node_pb2.ResponseMessage,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        node_pb2.HandShakeRequest,
        google.protobuf.empty_pb2.Empty,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        node_pb2.RootMessage,
        node_pb2.ResponseMessage,
    ],
]

class NodeServicesServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def handshake(
        self,
        request: node_pb2.HandShakeRequest,
        context: _ServicerContext,
    ) -> typing.Union[node_pb2.ResponseMessage, collections.abc.Awaitable[node_pb2.ResponseMessage]]: ...

    @abc.abstractmethod
    def disconnect(
        self,
        request: node_pb2.HandShakeRequest,
        context: _ServicerContext,
    ) -> typing.Union[google.protobuf.empty_pb2.Empty, collections.abc.Awaitable[google.protobuf.empty_pb2.Empty]]: ...

    @abc.abstractmethod
    def send(
        self,
        request: node_pb2.RootMessage,
        context: _ServicerContext,
    ) -> typing.Union[node_pb2.ResponseMessage, collections.abc.Awaitable[node_pb2.ResponseMessage]]: ...

def add_NodeServicesServicer_to_server(servicer: NodeServicesServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
